const categoryMiddleware = require("../../middlewares/client/category.middleware");
const cartMiddleware = require("../../middlewares/client/cart.middleware");
const userMiddleware = require("../../middlewares/client/user.middleware");
const settingMiddleware = require("../../middlewares/client/setting.middleware");
const productRouters = require("./product.route");
const homeRouters = require("./home.route");
const searchRouters = require("./search.route");
const cartRoutes = require("./cart.route");
const checkoutRoutes = require("./checkout.route");
const chatRoutes = require("./chat.route");
const userRoutes = require("./user.route");
const usersRoutes = require("./users.route");
module.exports = (app) => {
  app.use(settingMiddleware.settingGeneral);
  app.use(categoryMiddleware.category);
  app.use(cartMiddleware.cartId);
  app.use(userMiddleware.infoUser);
  app.use("/", homeRouters);
  app.use("/products", productRouters);
  app.use("/search", searchRouters);
  app.use("/cart", cartRoutes);
  app.use("/checkout", checkoutRoutes);
  app.use("/user", userRoutes);
  app.use("/chat", chatRoutes);
  app.use("/users", usersRoutes);
};
